from exception import AuthException


class NotPermittedErrorException(AuthException):
    pass