from exception import AuthException


class PermissionErrorException(AuthException):
    pass